---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: version-scanner-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["project.openshift.io"]
  resources: ["projects"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: version-scanner-global-binding
subjects:
- kind: ServiceAccount
  name: default       # Nazwa SA
  namespace: default  # Namespace SA
roleRef:
  kind: ClusterRole
  name: version-scanner-role
  apiGroup: rbac.authorization.k8s.io


oc auth can-i list deployments --all-namespaces --as=system:serviceaccount:default:default