---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Nazwa roli opisująca jej funkcję
  name: version-reader-cluster-role
rules:
- apiGroups: ["apps"]
  # Dostęp do Deploymentów i StatefulSetów, gdzie zaszyte są wersje obrazów
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  # Dodatkowo dostęp do listowania projektów (namespaces), 
  # aby skrypt wiedział, jakie projekty istnieją na klastrze
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-versions-globally-binding
subjects:
- kind: ServiceAccount
  # TUTAJ WPISZ NAZWĘ SWOJEGO SERVICE ACCOUNT
  name: default
  # TUTAJ WPISZ PROJEKT (NAMESPACE), W KTÓRYM JEST TEN SERVICE ACCOUNT
  namespace: default
roleRef:
  kind: ClusterRole
  name: version-reader-cluster-role
  apiGroup: rbac.authorization.k8s.io