apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-lenovo-prometheus
provisioner: <TU_WSTAW_PROVISIONER_NAME_Z_OPERATORA>
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
