apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-lenovo-prometheus
provisioner: lenovo.nfs        # ⬅️ NAZWA Z POLA provisionerName
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"
