lvms-kafka.yaml


apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvms-kafka
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - name: kafka
      nodeSelector:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kafka-node
            operator: In
            values:
            - "true"
      deviceSelector:
        paths:
        - /dev/vdb
      thinPoolConfig:
        name: thin-pool-kafka
        sizePercent: 90
        overprovisionRatio: 10



sc-lvms-kafka.yaml:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lvms-kafka-thin
provisioner: topolvm.io
parameters:
  device-class: kafka
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true


oc get sc lvms-kafka-thin


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-lvms
spec:
  storageClassName: lvms-kafka-thin
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

oc -n openshift-lvm-storage patch lvmcluster lvms-kafka -p '{"metadata":{"finalizers":[]}}' --type=merge
