lvms-kafka.yaml


apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvms-kafka
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - name: kafka
      nodeSelector:
        kafka-node: "true"
      deviceSelector:
        paths:
        - /dev/vdb
      thinPoolConfig:
        name: thin-pool-kafka
        sizePercent: 90
        overprovisionRatio: 10


sc-lvms-kafka.yaml:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lvms-kafka-thin
provisioner: topolvm.io
parameters:
  device-class: kafka
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true


oc get sc lvms-kafka-thin