apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-request-zst
  namespace: openshift-config
objects:

  # 1. Tworzenie projektu
  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      name: "${PROJECT_NAME}"
      annotations:
        openshift.io/description: "${PROJECT_DESCRIPTION}"
        openshift.io/display-name: "${PROJECT_DISPLAYNAME}"

  # 2. Automatyczny RoleBinding nadający admina grupie zst
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: zst-admin-binding
      namespace: "${PROJECT_NAME}"
    subjects:
      - kind: Group
        name: "zst"
    roleRef:
      kind: Role
      name: admin
      apiGroup: rbac.authorization.k8s.io

parameters:
  - name: PROJECT_NAME
    required: true
  - name: PROJECT_DISPLAYNAME
    required: false
  - name: PROJECT_DESCRIPTION
    required: false

#######################################################

oc apply -f project-template-zst.yaml
oc patch project.config.openshift.io/cluster --type=merge -p \
'{"spec":{"projectRequestTemplate":{"name":"project-request-zst"}}}'
oc adm policy add-cluster-role-to-group self-provisioner zst
