apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: TWOJA_NAZWA_NAMESPACE
  name: deployment-manager
rules:
- apiGroups: ["apps"]     # Grupa API dla Deploymentów
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]